### PR TITLE
Create Turkish Translation

### PR DESCRIPTION
**Pull request by Fyoncle**
:)

### CODE REVIEW

**Comment by Fyoncle** [comment]
❤️

**Comment by tr7zw** [comment]
Just be aware, that the next release will take some time. Usually don't do releases just for lang files^^

**Comment by tr7zw** [comment]
Good chance it will happen with 1.21.2. But since I build for all [these ](https://github.com/tr7zw/WaveyCapes/blob/main/settings.json)versions at once, 1.20.1 will get it too :D

**Comment by Fyoncle** [comment]
> Good chance it will happen with 1.21.2. But since I build for all [these ](https://github.com/tr7zw/WaveyCapes/blob/main/settings.json)versions at once, 1.20.1 will get it too :D

Yay! Thank you :D

Your mod is awesome! Adding life to my every single world! Doesn't matter if its survival, PvP or anything!

**Pull request merged**
